import type { Metadata, Viewport } from "next";
import Agents from "@/components/home-v6/sections/Agents";
import Announcement from "@/components/home-v6/sections/Announcement";
import { Commitments, Essay } from "@/components/home-v6/sections/Bands";
import { Closing, Footer, SectionClosing } from "@/components/home-v6/sections/Closing";
import { CommitmentCards, Coverage } from "@/components/home-v6/sections/Coverage";
import Faq from "@/components/home-v6/sections/Faq";
import Hero from "@/components/home-v6/sections/Hero";
import HowItWorks from "@/components/home-v6/sections/HowItWorks";
import Product from "@/components/home-v6/sections/Product";
import HashRedirect from "@/components/home-v6/HashRedirect";
import ScrollRouter from "@/components/home-v6/ScrollRouter";
import SiteHeader from "@/components/home-v6/SiteHeader";
import JsonLd from "@/components/site/JsonLd";
import SkipLink from "@/components/site/SkipLink";
import { V6_DESCRIPTION, V6_TITLE } from "@/content/home-v6";
import { CLEAN_URLS, SCROLL_SECTIONS, SECTION_PAGES } from "@/lib/flags";
import { HOME_URL, SITE_NAME } from "@/lib/site";
import { V6_FONT_VARIABLES } from "./fonts";
import { V6_JSON_LD } from "./structuredData";
import "./v6.css";

/**
 * Homepage v6 (light design system), served at "/" when NEXT_PUBLIC_FF_HOMEPAGE_V6 is on (next.config.ts).
 * Source: Claude Design "Crado Homepage v6.dc.html". The Open Graph and Twitter images are generated by
 * src/app/(home)/opengraph-image.tsx and twitter-image.tsx.
 */
export const metadata: Metadata = {
  title: { absolute: V6_TITLE },
  description: V6_DESCRIPTION,
  robots: { index: true, follow: true, "max-image-preview": "large" },
  openGraph: { type: "website", siteName: SITE_NAME, title: V6_TITLE, description: V6_DESCRIPTION },
  twitter: { card: "summary_large_image", title: V6_TITLE, description: V6_DESCRIPTION },
};

export const viewport: Viewport = {
  colorScheme: "light",
  themeColor: "#F8F7F6",
};

export default function HomePage() {
  return (
    <div data-home-v6 className={`${V6_FONT_VARIABLES} overflow-x-clip bg-v6-page font-v6-sans text-[length:var(--v6-body)] leading-(--v6-body-lh) font-normal text-v6-ink [font-variant-numeric:normal] [-webkit-font-smoothing:auto] [-moz-osx-font-smoothing:auto]`}>
      {/* React hoists these into <head>. Next normalises a "/" canonical to the bare origin, so it is written here. */}
      <link rel="canonical" href={HOME_URL} />
      <meta property="og:url" content={HOME_URL} />
      {V6_JSON_LD.map((d) => (
        <JsonLd key={d["@type"]} data={d} />
      ))}
      {SECTION_PAGES && <HashRedirect />}
      {SCROLL_SECTIONS && <ScrollRouter />}
      <SkipLink target="main" />
      <Announcement />
      <SiteHeader />
      <main id="main">
        <Hero />
        <Commitments />
        <Essay />
        <HowItWorks teaser={SECTION_PAGES} />
        <Product />
        <Agents teaser={SECTION_PAGES} />
        <Coverage teaser={SECTION_PAGES} />
        <CommitmentCards />
        {/* Client component: props only when on, so the flag-off page data stays exactly as before. */}
        <Faq {...(SECTION_PAGES ? { teaser: true } : SCROLL_SECTIONS ? { routed: true } : {})} />
        {CLEAN_URLS ? <SectionClosing /> : <Closing />}
      </main>
      <Footer />
    </div>
  );
}
